// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHrWDPetgCuuUI49O0queziZmWgqB2Gc',
    appId: '1:1079090364682:web:919878fd10c91cdfb3baf3',
    messagingSenderId: '1079090364682',
    projectId: 'todoapp-f68fa',
    authDomain: 'todoapp-f68fa.firebaseapp.com',
    storageBucket: 'todoapp-f68fa.appspot.com',
    measurementId: 'G-2WXW9TRZYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDse2SWV-CP4A9Vl2pjetOHwvO9iP0zc_g',
    appId: '1:1079090364682:android:2418258c7399ad8db3baf3',
    messagingSenderId: '1079090364682',
    projectId: 'todoapp-f68fa',
    storageBucket: 'todoapp-f68fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIG8vfuHu7WbaNfvnHxigbHuv3CkXdg0',
    appId: '1:1079090364682:ios:b384c351742ae4c6b3baf3',
    messagingSenderId: '1079090364682',
    projectId: 'todoapp-f68fa',
    storageBucket: 'todoapp-f68fa.appspot.com',
    iosClientId: '1079090364682-thr7fbtrsa3nsge5gadjkocrfi0it9lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIG8vfuHu7WbaNfvnHxigbHuv3CkXdg0',
    appId: '1:1079090364682:ios:679b3bf1b362181ab3baf3',
    messagingSenderId: '1079090364682',
    projectId: 'todoapp-f68fa',
    storageBucket: 'todoapp-f68fa.appspot.com',
    iosClientId: '1079090364682-1u7j55mc134taiam22e2d21mm111vduk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
